### ISSUE TITLE
[Bug report]Missed library in examples

### ISSUE THREAD

**Issue by yl-wang996** [kevinzakka/mink#11]
For example, at [here](https://github.com/kevinzakka/mink/blob/505cd88911d76705c5f930869810b476b7a4027d/examples/arm_ur5e.py#L6), it seems the `loop_rate_limiters` has not been defined at somewhere.

Please consider putting `pip install loop-rate-limiters` in your installation scripts.

**Comment by kevinzakka** [comment]
Hi @yl-wang996, for the examples, you'll want to run:

```bash
pip install "mink[examples]"
```

as mentioned in the README and documentation.

Let me know if that fixes your problem.

**Comment by yl-wang996** [comment]
sorry, My fault.  Thanks for your fast response. It was resolved.
